apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Orim2002/linker
    targetRevision: main
    path: helm
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: linker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
